# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/DEFFS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/DEFFS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/DEFFS/CMakeFiles /home/pi/Desktop/DEFFS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/DEFFS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DEFFS

# Build rule for target.
DEFFS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DEFFS
.PHONY : DEFFS

# fast build rule for target.
DEFFS/fast:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/build
.PHONY : DEFFS/fast

src/arguments.o: src/arguments.c.o

.PHONY : src/arguments.o

# target to build an object file
src/arguments.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/arguments.c.o
.PHONY : src/arguments.c.o

src/arguments.i: src/arguments.c.i

.PHONY : src/arguments.i

# target to preprocess a source file
src/arguments.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/arguments.c.i
.PHONY : src/arguments.c.i

src/arguments.s: src/arguments.c.s

.PHONY : src/arguments.s

# target to generate assembly for a file
src/arguments.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/arguments.c.s
.PHONY : src/arguments.c.s

src/attr.o: src/attr.c.o

.PHONY : src/attr.o

# target to build an object file
src/attr.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/attr.c.o
.PHONY : src/attr.c.o

src/attr.i: src/attr.c.i

.PHONY : src/attr.i

# target to preprocess a source file
src/attr.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/attr.c.i
.PHONY : src/attr.c.i

src/attr.s: src/attr.c.s

.PHONY : src/attr.s

# target to generate assembly for a file
src/attr.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/attr.c.s
.PHONY : src/attr.c.s

src/crypto.o: src/crypto.c.o

.PHONY : src/crypto.o

# target to build an object file
src/crypto.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/crypto.c.o
.PHONY : src/crypto.c.o

src/crypto.i: src/crypto.c.i

.PHONY : src/crypto.i

# target to preprocess a source file
src/crypto.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/crypto.c.i
.PHONY : src/crypto.c.i

src/crypto.s: src/crypto.c.s

.PHONY : src/crypto.s

# target to generate assembly for a file
src/crypto.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/crypto.c.s
.PHONY : src/crypto.c.s

src/deffs.o: src/deffs.c.o

.PHONY : src/deffs.o

# target to build an object file
src/deffs.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/deffs.c.o
.PHONY : src/deffs.c.o

src/deffs.i: src/deffs.c.i

.PHONY : src/deffs.i

# target to preprocess a source file
src/deffs.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/deffs.c.i
.PHONY : src/deffs.c.i

src/deffs.s: src/deffs.c.s

.PHONY : src/deffs.s

# target to generate assembly for a file
src/deffs.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/deffs.c.s
.PHONY : src/deffs.c.s

src/perms.o: src/perms.c.o

.PHONY : src/perms.o

# target to build an object file
src/perms.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/perms.c.o
.PHONY : src/perms.c.o

src/perms.i: src/perms.c.i

.PHONY : src/perms.i

# target to preprocess a source file
src/perms.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/perms.c.i
.PHONY : src/perms.c.i

src/perms.s: src/perms.c.s

.PHONY : src/perms.s

# target to generate assembly for a file
src/perms.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/perms.c.s
.PHONY : src/perms.c.s

src/rw.o: src/rw.c.o

.PHONY : src/rw.o

# target to build an object file
src/rw.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/rw.c.o
.PHONY : src/rw.c.o

src/rw.i: src/rw.c.i

.PHONY : src/rw.i

# target to preprocess a source file
src/rw.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/rw.c.i
.PHONY : src/rw.c.i

src/rw.s: src/rw.c.s

.PHONY : src/rw.s

# target to generate assembly for a file
src/rw.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/rw.c.s
.PHONY : src/rw.c.s

src/utils.o: src/utils.c.o

.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/DEFFS.dir/build.make CMakeFiles/DEFFS.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... DEFFS"
	@echo "... edit_cache"
	@echo "... src/arguments.o"
	@echo "... src/arguments.i"
	@echo "... src/arguments.s"
	@echo "... src/attr.o"
	@echo "... src/attr.i"
	@echo "... src/attr.s"
	@echo "... src/crypto.o"
	@echo "... src/crypto.i"
	@echo "... src/crypto.s"
	@echo "... src/deffs.o"
	@echo "... src/deffs.i"
	@echo "... src/deffs.s"
	@echo "... src/perms.o"
	@echo "... src/perms.i"
	@echo "... src/perms.s"
	@echo "... src/rw.o"
	@echo "... src/rw.i"
	@echo "... src/rw.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

